### ISSUE TITLE
Unknown from most sensors

### ISSUE THREAD

**Issue by andykorol1** [nathanmarlor/foxess_em#362]
## Version of the custom_component

V1.9.1

## Configuration

Config file has no settings for this integration. 

## Describe the bug

"Unknown" is showing next to all sensors except for the solcast ones. I've attached a screenshot to show and attached some logs.

## Debug log

Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:584
integration: Recorder (documentation, issues)
First occurred: 3:30:59 PM (4 occurrences)
Last logged: 3:55:08 PM

State attributes for sensor.foxess_em_forecast exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/foxess_em/average/average_model.py:93
integration: FoxESS - Energy Management (documentation, issues)
First occurred: 3:31:12 PM (1 occurrences)
Last logged: 3:31:12 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/foxess_em/average/average_controller.py", line 70, in async_refresh
    await self._model.refresh()
  File "/config/custom_components/foxess_em/average/average_model.py", line 44, in refresh
    await self._update_history(self._tracked_sensors[sensor])
  File "/config/custom_components/foxess_em/average/average_model.py", line 55, in _update_history
    await self._update_item(item)
  File "/config/custom_components/foxess_em/average/average_model.py", line 93, in _update_item
    values_dict[0] = {
    ~~~~~~~~~~~^^^
IndexError: list assignment index out of range

![Screenshot 2024-03-14 155826](https://github.com/nathanmarlor/foxess_em/assets/111964964/7424b80d-3f30-45b2-bb64-123d54923ff9)


```

**Comment by andykorol1** [comment]
Appears to be fixed after a couple of uninstalls and re boots
